Nazariglez/notan

crates/notan_app/src/empty.rs, crates/notan_draw/src/images/painter.rs, crates/notan_draw/src/shapes/ellipse.rs, crates/notan_draw/src/transform.rs, crates/notan_egui/src/extension.rs, crates/notan_glow/src/buffer.rs, crates/notan_glow/src/lib.rs, crates/notan_glow/src/pipeline.rs, crates/notan_glow/src/texture.rs, crates/notan_glow/src/to_glow.rs, crates/notan_graphics/src/device.rs, crates/notan_graphics/src/pipeline.rs, crates/notan_graphics/src/texture.rs, crates/notan_math/src/constants.rs, examples/draw_shader.rs, examples/draw_transform.rs, examples/draw_transform_local.rs, examples/renderer_postprocess.rs, examples/renderer_render_texture.rs, examples/renderer_texture.rs, examples/renderer_textured_cube.rs
- VAOs doesn't keep older attribute pointers anymore after a new VAO is bind
- Textures can use Wrap modes now
- Increased textures slots per shader from 8 to 16
- Deprecated `math::DEG_TO_RAD` and `math::RAD_TO_DEG`
- Textures need to be declared on the pipeline with the location ID
=> Fixed and improved some low level rendering code

crates/notan_app/src/backend.rs, crates/notan_app/src/empty.rs, crates/notan_input/src/mouse.rs, crates/notan_web/src/mouse.rs, crates/notan_web/src/touch.rs, crates/notan_web/src/utils.rs, crates/notan_web/src/window.rs, crates/notan_winit/src/window.rs
* added `Window::set_capture_cursor` and `Window::capture_cursor` to confine the cursor into the window's app
* Added `app.mouse.wheel_delta` to read the delta without check the event loop
=> Added capture cursor feature to lock the cursor inside the window's app

Cargo.lock, Cargo.toml, crates/notan_graphics/Cargo.toml, crates/notan_graphics/src/buffer.rs, crates/notan_graphics/src/device.rs, crates/notan_graphics/src/lib.rs, crates/notan_graphics/src/render_texture.rs, crates/notan_graphics/src/renderer.rs, crates/notan_graphics/src/texture.rs, crates/notan_graphics/src/to_file.rs, crates/notan_utils/Cargo.toml, crates/notan_utils/src/lib.rs, crates/notan_utils/src/save_file.rs
This PR adds `Texture::to_file` and `RenderTexture::to_file` to export as png the content of the textures. 
It also adds some debug checks to warn the user when do something silly with Graphics that it can cause undefined behavior.
=> Added ' texture_to_file' feature to save as png textures or render textures 

crates/notan_app/src/backend.rs, crates/notan_app/src/config.rs, crates/notan_app/src/empty.rs, crates/notan_web/src/window.rs, crates/notan_winit/src/window.rs
This PR enables a window to be always on top.
This feature is both present at window creation and can be toggled while running (similar to fullscreen)
=> Enable always on top for window

CHANGELOG.md, crates/notan_egui/src/plugin.rs
Hey!
currently, command key is ignored on mac when targeting web
to fix we can set `mac_cmd` and `command` similar to how [eframe does it](https://github.com/emilk/egui/blob/master/crates/eframe/src/web/input.rs#L204-L210)
=> [egui] accept cmd key on web

crates/notan_web/src/mouse.rs
Hey! mouse wheel in notan_web seems inverted when compared with notan_winit
in both examples below I'm dragging two fingers on trackpad first to the right, and then to the left
**winit 👇**
https://user-images.githubusercontent.com/15520960/192139878-b693f140-f2fe-4f5a-a057-6103a7a3e725.mov
**web 👇**
https://user-images.githubusercontent.com/15520960/192140085-1c0ef801-f3a5-4a0a-a8c7-9a6409a43470.mov
to fix we can do what winit [does on web](https://github.com/rust-windowing/winit/blob/master/src/platform_impl/web/web_sys/event.rs#L51-L52) and reverse incoming deltas
=> fix inverted mouse wheel on web

crates/notan_input/src/keyboard.rs
Hi there, very small PR. Just noticed a typo from the linting of one of the docstrings. Hope this helps, thanks! :)
=> Typo in docstring

crates/notan_glow/src/lib.rs
needed for creating custom TextureSources -> https://github.com/Nazariglez/notan/blob/develop/crates/notan_glow/src/html_image.rs#L32
another option, in case we don't wanna expose, is for each backend to `pub TextureKey` which then can become the return type of `TextureSource>create`, and `add_inner_texture` or equivalent is handled by backends
=> expose add_inner_texture in GlowBackend

crates/notan_app/src/config.rs, crates/notan_winit/src/window.rs
Just adding an option so mouse events will passthrough the window.
This is useful if you want to create an overlay using transparent, always on top, and mouse_passthrough window options.
It uses a feature of Winit to achieve this.
=> Mouse passthrough option

crates/notan_macro/src/lib.rs
This is a small PR to address https://github.com/Nazariglez/notan/issues/159
I did some digging and found that clippy will let you `allow` certain lints and hence silence them from clippy's output. Adding this `allow` macro to main in a given example doesn't seem to work however appending it to the computed output of `#[notan_main]` seems to fix the issue.
Running any example/program with notan (e.g. `cargo clippy --example window_open`) would produce...
```sh
warning: recursing into entrypoint `main`
--> examples/window_open.rs:4:4
|
4 | fn main() -> Result<(), String> {
|    ^^^^
|
= note: `#[warn(clippy::main_recursion)]` on by default
= help: consider using another function for this recursion
= help: for further information visit …
```
=> Allow clippy::main_recursion lint

crates/notan_app/src/empty.rs, crates/notan_glow/src/buffer.rs, crates/notan_glow/src/lib.rs, crates/notan_glow/src/to_glow.rs, crates/notan_graphics/src/buffer.rs, crates/notan_graphics/src/device.rs, examples/renderer_quad.rs
=> Allow u16 index buffers

Cargo.lock, Cargo.toml, crates/notan_macro/Cargo.toml, crates/notan_macro/src/lib.rs, crates/notan_macro/src/shaders.rs
adds two new [mutually exclusive](https://doc.rust-lang.org/cargo/reference/features.html#mutually-exclusive-features) features, `glsl-to-spirv` and `shaderc` to notan and notan_macro
my first time playing with `features` though, so pls yell if anything feels off :)
=> add ability to toggle b/w glsl-to-spirv and shaderc

crates/notan_app/src/backend.rs, crates/notan_app/src/empty.rs, crates/notan_web/src/window.rs, crates/notan_winit/src/window.rs
- A small change so you can toggle mouse passthrough on and off with `app.window().set_mouse_passthrough(bool)`
- Also added the ability to return the window id
=> Mouse passthrough toggle

crates/notan_egui/src/input.rs
Adds the function keys to notan_egui's `to_egui_key` function.
=> Add function keys to notan_egui

crates/notan_graphics/src/device.rs
Assert that the provided buffer is at least the size of the bytes to be read, which may be smaller than the texture's buffer size.
=> Fix debug assert in Device::inner_read_pixels

CHANGELOG.md, crates/notan_app/src/backend.rs, crates/notan_app/src/empty.rs, crates/notan_draw/src/draw.rs, crates/notan_draw/src/manager.rs, crates/notan_draw/src/texts/text.rs, crates/notan_web/src/window.rs, crates/notan_winit/src/window.rs
- Added `WindowBackend::set_title` and `WindowBackend::title` to change or get the title at any time.
- Improved stencil clearing when setting a mask on the draw api at the end of the pass.
- Fix panic using Draw API to draw text with `max_width` and `size` as 0. 
fixes #221 #238
=> Minor fixes and improvements.

crates/notan_app/src/config.rs, crates/notan_winit/src/window.rs, examples/window_icon_from_raw.rs
This Pull-Request implements the feature requested in #215
Change Log:
- Added set_window_icon_data to WindowConfig
- Added set_taskbar_icon_data to WindowConfig
- Added window_icon_from_raw.rs Example
Example Usage:
```rust
use notan::prelude::*;
#[notan_main]
fn main() -> Result<(), String> {
// Check the documentation for more options
let window_config = WindowConfig::new()
.set_title("Window Icon Data Demo")
.set_window_icon_data(Some(include_bytes!("./examples/assets/rust.ico")))
.set_taskbar_icon_data(Some(include_bytes!("./examples/assets/rust.ico")));
notan::init().add_config(window_config).build()
}
```
(This is my first Pull Request to this crate)
=> Added ability to set Window/Taskbar icon from raw data

CHANGELOG.md, crates/notan_app/src/config.rs, crates/notan_winit/src/window.rs, examples/renderer_instancing_cubes.rs
This allows a window to spawn at the specified position and wont lead to odd "jumping" behavior we see right now after setting the position after window creation.
Clamping logic is from here: https://github.com/Shel-M/egui/blob/master/crates/egui-winit/src/window_settings.rs#LL91C10-L91C10
=> add support for passing a window position upon creation

CHANGELOG.md, crates/notan_macro/src/handlers.rs, crates/notan_winit/src/gl_manager.rs
So, I came up with this very simple patch for the error: "extension to create ES context with wgl is not present" #289 . I tested it out on three operating systems - my main PC which runs windows 10 and macOS with dual boot. The gotten configurations seem to be correct. Also tested this out on a laptop that runs windows 11, everything also seems to be correct and working.
closes #289
=> Fix for "extension to create ES context with wgl is not present"

crates/notan_draw/src/lib.rs
In order to be able to use the `DrawProcess` trait from the `builder` module in the `notan_draw` crate from _user code_.
I've leveraged this patch to implement custom drawing features on the `Draw` instance.
=> expose notan_draw builder publicly to allow custom builders

crates/notan_app/src/app.rs
Right now it is used in many examples, fully documented, but not publicly accesible.
=> make AppTimer public

Cargo.toml, crates/notan_draw/src/shapes.rs, crates/notan_draw/src/shapes/point.rs, examples/draw_points.rs
Hi! Testing notan I missed being able to draw points in a simple way with variable width and alignment, so I created a Point shape, and two enums for alignment, since it didn't seem appropriate to reuse the ones intended for text.
I also made an example showcasing all the alignment combinations on the first 10 integral widths, showing labels when compiled with text support:
Please feel free of letting me know if you want me to change something.
=> Add support for drawing points

README.md
Hosting the gifs on Giphy.com, instead of Gfycat.com.
closes #295
=> Update README.md (The gifs now work again)

Cargo.lock, Cargo.toml, crates/notan_egui/Cargo.toml, crates/notan_egui/README.md
This updates notan-egui to use egui 0.27.2, I also separated the version of the notan-egui crate from the workspace version, as I didn't think it made sense to update it when there are no changes to the main crate itself, happy to revert that though and just bump all.
=> Update egui to 0.27.2

Cargo.lock, Cargo.toml, crates/notan_egui/Cargo.toml, crates/notan_egui/src/plugin.rs
Don't know if you want this but I ran into some difficulties with `egui` versioning between crates, so I ended up bumping the `egui` version.
Tested on Linux and MACOS using the `scrolling` section of the `egui` demo example. Behavior seems okay on both.
Don't know what the behavior on Windows looks like.
Not sure about some of the arguments, (`egui::MouseWheelUnit::Point` was chosen because it seems the most logical and seems to work well).
=> Bump egui crate to 0.28.1

crates/notan_egui/src/extension.rs, crates/notan_egui/src/plugin.rs
Fixes #338.  Seems to work both natively and in the browser.  Summary:
- The screen rect needs to be divided by the zoom factor before passing it to egui.
- The rects returned by egui then need to be scaled by the zoom factor.
- Egui's "zoom with keyboard" should be disabled by default in the browser since the browser already handles zoom (and uses the same keyboard shortcut).
- In raw_input, native_pixels_per_point needs to be set, or else the text looks pixelated when zooming in in the browser.
=> Support for egui_zoom_factor

README.md, xtask/res/example.html
When using the example html file, if the canvas is larger than the browser window, then scrolling does not work properly.  The top or left of the canvas is cut off.  Adding "safe" to the alignment in the css fixes the issue.
More information here:
https://stackoverflow.com/questions/33454533/cant-scroll-to-top-of-flex-item-that-is-overflowing-container
=> fix scrolling in example html

crates/notan_glow/src/buffer.rs
The value of glow::MAX_UNIFORM_BLOCK_SIZE can be arbitrarily large. For instance on Firefox on Linux with AMD GPUs tends to generate quite large values: 2\*\*29 on RX 550, and 2\*\*31 on RX 7600 XT, which will result in this function trying to create a 0.5 GB and a 2 GB buffer respectively. Creating buffers this large will either cause a quick OOM, or at least make the application unusably slow.
This commit caps the returned size to 2\*\*16, which is the value returned by Chromium in the same combination as above and results in this function creating 64 kB buffers.
=> Cap InnerBuffer::global_ubo size

crates/notan_glow/src/pipeline.rs, crates/notan_glow/src/to_glow.rs, crates/notan_graphics/src/pipeline.rs
Simple pull request to add support for drawing Points as a primitive as well as support for using `gl_PointSize` in the vertex shader. Sorry if I missed anything, I don't know much about OpenGL. However I've used it in my own toy project and it works (not sure how much of an assurance that is)
Now you should be able to make a pipeline that has gl_PointSize support by doing
```rust
let pipeline = gfx.create_pipeline()
.from(&VERTEX, &FRAGMENT)
.with_vertex_info(&vertex_info)
.with_point_size_available(true) // note
.build()
.unwrap();
```
And you should be able to draw points by doing
```rust
renderer.set_primitive(DrawPrimitive::Points);
```
=> Add support for GL_POINTS and gl_PointSize
