crates/notan_app/src/backend.rs, crates/notan_app/src/builder.rs, crates/notan_app/src/config.rs, crates/notan_app/src/empty.rs, crates/notan_web/src/backend.rs, crates/notan_web/src/files.rs, crates/notan_web/src/keyboard.rs, crates/notan_web/src/mouse.rs, crates/notan_web/src/window.rs, crates/notan_winit/src/backend.rs, crates/notan_winit/src/window.rs, examples/egui_demo.rs, examples/egui_shape_widget.rs
This PR adds an option to stop the thread or the execution loop until an input event arrives. Quite useful for apps, to avoid consuming CPU when there is nothing to render or process.
=> Added a lazy_loop more. Close #81

Cargo.lock, crates/notan_log/Cargo.toml, crates/notan_log/src/config.rs
Fixes https://github.com/Nazariglez/notan/security/dependabot/1
Also logs now uses UTC time and the format is always `[year]-[month]-[day] [hour]:[minutes]:[days]`
=> Removed chrono due a security issue

crates/notan_egui/README.md, crates/notan_egui/src/extension.rs, crates/notan_glow/src/lib.rs, examples/egui_paint.rs
* Fixed viewport issues where the Y axis was inverted and wasn't using DPI to calculate min positon
* fixed #93
=> Fixed EGUI 0.18.1 Paint callback feature 

Cargo.lock, crates/notan_app/src/builder.rs, crates/notan_app/src/graphics.rs, crates/notan_graphics/Cargo.toml, crates/notan_graphics/src/buffer.rs, crates/notan_graphics/src/device.rs, crates/notan_graphics/src/lib.rs, crates/notan_macro/src/lib.rs, examples/egui_render_texture.rs, examples/renderer_cube.rs, examples/renderer_instancing_cubes.rs, examples/renderer_postprocess.rs, examples/renderer_textured_cube.rs, examples/renderer_uniform_std140.rs, src/prelude.rs
* _Breaking change_
* Glam types can be used uniforms directly
* Added the macro `uniform` to define structs that are serialized as std140 automatically
=> Improved how the Uniform buffer data upload data tot he gpu

crates/notan_draw/src/builder.rs, crates/notan_draw/src/draw.rs, crates/notan_draw/src/transform.rs, crates/notan_input/src/mouse.rs, crates/notan_math/src/constants.rs, crates/notan_math/src/lib.rs, crates/notan_math/src/utils.rs, examples/input_mouse_local_position.rs
=> Improve how the screen_to_local and local_to_screen works for the Draw2d API

examples/game_15_puzzle.rs
fixes #124.
To generate solvable arrangement, I simply move randomly from an initial board.
There will be some other methods, but I think this is straightforward.
=> fix `game_15_puzzle` example to generate valid arrangements

CHANGELOG.md
=> Update changelog for `always_on_top`

Cargo.lock, Cargo.toml, crates/notan_math/src/lib.rs, crates/notan_math/src/prelude.rs, crates/notan_random/Cargo.toml, crates/notan_random/README.md, crates/notan_random/src/lib.rs, crates/notan_random/src/prelude.rs, crates/notan_random/src/utils.rs, examples/game_15_puzzle.rs, src/lib.rs, src/prelude.rs
Hi! This PR reorganizes the random utils a bit. While having a built-in rand is of course a nice batteries-included convenience, some users might want to switch to sth smaller like nanorand and they should have that option.
=> Separate optional notam_random crate

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/notan_app/src/empty.rs, crates/notan_backend/src/lib.rs, crates/notan_backend/src/prelude.rs, crates/notan_core/src/events.rs, crates/notan_extra/src/fps_limit.rs, crates/notan_glow/Cargo.toml, crates/notan_glow/src/html_image.rs, crates/notan_glow/src/lib.rs, crates/notan_glow/src/prelude.rs, crates/notan_glow/src/render_target.rs, crates/notan_glow/src/texture.rs, crates/notan_glow/src/texture_source.rs, crates/notan_graphics/Cargo.toml, crates/notan_graphics/src/device.rs, crates/notan_graphics/src/texture.rs, crates/notan_macro/Cargo.toml, crates/notan_web/src/lib.rs, crates/notan_web/src/prelude.rs, crates/notan_winit/Cargo.toml, crates/notan_winit/src/lib.rs, crates/notan_winit/src/prelude.rs, examples/draw_image.rs, src/prelude.rs
=> Allow HtmlImagElement to be loaded (and potentially another texture types)

examples/input_keyboard.rs
Just a quick MR,
resolving a TODO in the `input_keyboard` example, and added a `const` for the speed, to allow for potential easier editing.
=> added delta and const for speed to the movement, resolving the TODO.

crates/notan_glow/src/to_glow.rs
catch-all match arms considered evil 😈
=> [notan_glow] fix VertexFormat mapping

Cargo.lock, Cargo.toml, crates/notan_egui/Cargo.toml, crates/notan_egui/src/extension.rs, crates/notan_egui/src/lib.rs, crates/notan_egui/src/plugin.rs, examples/egui_paint.rs
=> Updated EGUI to latest version

CHANGELOG.md, crates/notan_glow/src/html_image.rs, crates/notan_glow/src/lib.rs, crates/notan_glow/src/render_target.rs, crates/notan_glow/src/texture.rs, crates/notan_graphics/src/texture.rs
=> Mipmapping support

crates/notan_app/src/backend.rs, crates/notan_app/src/empty.rs, crates/notan_web/src/window.rs, crates/notan_winit/src/window.rs
This will allow you to set the position of the window in pixels.
Can now just do `app.window().set_position_pixels(400, 100);`
=> Setting window position

crates/notan_draw/src/extension.rs, crates/notan_draw/src/manager.rs
=> draw2d inverts the projection rendering to render_textures

Cargo.lock, crates/notan_draw/src/draw.rs, crates/notan_glyph/src/lib.rs, crates/notan_math/src/rect.rs, crates/notan_text/Cargo.toml, crates/notan_text/src/calculator.rs, crates/notan_text/src/lib.rs, examples/draw_text_bounds.rs, examples/text_bounds.rs, examples/text_hello.rs
This is kind of tricky. I am having some issues, some panics mixing different fonts, and sizes that are not equal in all frames...
So still I need to figure it a few things.
=> Get Text Bounds/Size

.github/workflows/rust.yml, src/lib.rs
a simple CI action that does some linting and runs tests ✨ 
mostly stolen from [here](https://github.com/actions-rs/example/blob/master/.github/workflows/quickstart.yml)
=> add a simple CI action

crates/notan_draw/src/batch.rs, crates/notan_draw/src/draw.rs, crates/notan_draw/src/images/image.rs, crates/notan_draw/src/manager.rs, crates/notan_draw/src/patterns/pattern.rs, crates/notan_draw/src/shapes/circle.rs, crates/notan_draw/src/shapes/ellipse.rs, crates/notan_draw/src/shapes/path.rs, crates/notan_draw/src/shapes/rect.rs, crates/notan_draw/src/shapes/triangle.rs, crates/notan_draw/src/texts/text.rs, crates/notan_graphics/src/device.rs, crates/notan_graphics/src/pipeline.rs, crates/notan_graphics/src/renderer.rs, examples/draw_blend_mode.rs
=> Draw2D API Allows now to set an alpha blending mode, and disable the color blend mode.

CHANGELOG.md, crates/notan_draw/src/texts/painter.rs
Fixes https://github.com/Nazariglez/notan/issues/196
Will just do a check and stop it from panicking, instead it will simply not draw the text.
=> Drawing text no longer panics with invalid chars

crates/notan_egui/src/extension.rs
Updates `notan_egui` to use egui's new color space and simplifies rendering by getting rid of the need for webgl2-specific changes.
Fixes #197 and #158.
=> Update egui color space

crates/notan_winit/src/gl_manager.rs
=> Fixes how the GL Context is selected 

CHANGELOG.md, crates/notan_app/src/backend.rs, crates/notan_app/src/empty.rs, crates/notan_web/Cargo.toml, crates/notan_web/src/window.rs, crates/notan_winit/src/window.rs
=> Added methods on the window backend to get the screen's resolution

Cargo.lock, Cargo.toml, crates/notan_app/Cargo.toml, crates/notan_app/src/config.rs, crates/notan_core/Cargo.toml, crates/notan_core/src/events.rs, crates/notan_core/src/keyboard.rs, crates/notan_core/src/mouse.rs, crates/notan_input/Cargo.toml, crates/notan_input/src/keyboard.rs, crates/notan_input/src/mouse.rs, crates/notan_input/src/touch.rs, crates/notan_math/Cargo.toml, crates/notan_math/src/rect.rs
=> Added optional feature 'serde'  to serialize/deserialize some core types

crates/notan_draw/src/transform.rs, examples/draw_animation_list.rs, examples/draw_transform_local.rs, examples/egui_shape_widget.rs, examples/input_mouse_local_position.rs
=> fix matrix order of draw2d transforms

crates/notan_glow/src/buffer.rs, crates/notan_glow/src/lib.rs
=> fix: uniform buffers can be reused between pipelines

crates/notan_app/src/backend.rs, crates/notan_app/src/empty.rs, crates/notan_core/src/events.rs, crates/notan_egui/src/plugin.rs, crates/notan_input/src/mouse.rs, crates/notan_web/src/window.rs, crates/notan_winit/src/backend.rs, crates/notan_winit/src/mouse.rs, crates/notan_winit/src/window.rs
* Fixes to doc comments
* Added set cursor position
* Added mouse motion
https://osspial.github.io/winit/el2-win-joy/winit/event/device/index.html
=> Mouse motion and general fixes

CHANGELOG.md, examples/window_initial_position.rs
Small (maybe superfluous) example.
=> add example showing how to set initial window position

crates/notan_winit/src/window.rs
Cursor position was off center due to not taking into account high dpis
=> Fixed dpi issue with set_cursor_position

CHANGELOG.md, crates/notan_app/src/config.rs, crates/notan_egui/src/extension.rs, crates/notan_input/src/mouse.rs, crates/notan_winit/src/gl_manager.rs, examples/input_mouse_wheel.rs
Fixes: 
https://github.com/Nazariglez/notan/issues/267
https://github.com/Nazariglez/notan/issues/276
https://github.com/Nazariglez/notan/issues/269
=> Minor bug fixes

CHANGELOG.md, Cargo.lock, Cargo.toml, crates/notan_egui/Cargo.toml, crates/notan_egui/src/extension.rs, crates/notan_egui/src/lib.rs, crates/notan_egui/src/plugin.rs, crates/notan_macro/src/handlers.rs, examples/egui_render_texture.rs, examples/egui_texture.rs
=> update egui to 0.23.0

Cargo.lock, Cargo.toml, crates/notan_app/Cargo.toml, crates/notan_draw/Cargo.toml, crates/notan_glow/Cargo.toml, crates/notan_glyph/Cargo.toml, crates/notan_log/Cargo.toml, crates/notan_macro/Cargo.toml, crates/notan_math/Cargo.toml, crates/notan_oddio/Cargo.toml, crates/notan_random/Cargo.toml, crates/notan_winit/Cargo.toml
I need to fix some breakings, this may make it for 0.11.
=> WIP: upgrade deps

crates/notan_winit/src/backend.rs, crates/notan_winit/src/window.rs
=> Fixed window lazy loop when requesting frames

crates/notan_egui/src/plugin.rs
=> fix egui blurry text

crates/notan_glow/src/texture.rs, crates/notan_graphics/src/texture.rs
Adding RGB24 format to allow my use-case of rendering RGB video data without requiring conversion.
=> Add Rgb24 format.

crates/notan_draw/src/draw.rs
=> fix text transformation order

Cargo.lock, Cargo.toml, crates/notan_egui/Cargo.toml, crates/notan_egui/src/plugin.rs, examples/egui_custom_font.rs, examples/egui_render_texture.rs
This PR updates `egui` to 0.30.0.
=> chore: update egui to 0.31.0
